---
- hosts: server
  user: {{ user }}
  become: yes
  gather_facts: true
  pre_tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  vars_files:
    - vars/base_vars.yml

  roles:
    - { role: configure-server, tags: ['server'] }